# Custom Language File for Launcher Customizer

[ejs.app]
title = "Mintia Launcher"

[ejs.landing]
mediaLinkURL = "#"
mediaGitHubURL = "https://github.com/ppaka/MintiaLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/ppaka/MintiaLauncher"
supportLink = "https://github.com/ppaka/MintiaLauncher/issues"

[ejs.welcome]
welcomeHeader = "Mintia Launcher"
welcomeDescription = "Mintia Launcher를 실행해주셔서 감사합니다! 만약, 당신이 운명적으로 이 프로젝트를 발견하게 되신거라면 크게 도움은 안될 수도 있으니 너무 큰 기대는 하지 말아주세요.. 이 런처에 표시되는 서버들은 화이트리스트로 운영될거니까요!"
welcomeDescCTA = "(서버가 추가되고 지워지는 건 작성자 마음대로입니다)"
